#!/bin/bash

echo "╓Setup"

_log()
{
    echo "╠═$1"
}

export -f _log

if [ "$(uname -s)" == "Darwin" ]; then
    . ./installers/install-darwin.sh
else
    . ./installers/install-linux.sh
fi

if [ ! -d "$HOME/.tmux/plugins" ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    tmux source ~/.tmux.conf
    _log "Tmux plugin manager installed"
fi

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    _log "Plug vim installed for vim"
fi

if [ ! -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    _log "Plug vim installed for nvim"
fi

echo "╙Finished"

figlet dotfiles
cowsay Dotfiles finished!
